apiVersion: v1
kind: Service
metadata:
  name: {{ include "testchart.ResourceName" . }}-service
  labels:
    {{- include "testchart.commonlabels" . }}
    helm.sh/chart: {{ .Chart.Name }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 31231
  selector:
    {{- include "testchart.selectorlabels" . }}