# Default values for samplehelmapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: praravind1801/helmimages
  pullPolicy: IfNotPresent
  tag: "1.0.0"

service:
  type: NodePort
  port: 80
  nodePort: 32322
