{{- $releaseName := .Values.resultapp.name -}}
apiVersion: v1
kind: Service 
metadata:
  name: {{ $releaseName }}-service
  labels:
    {{- include "resultapp.Labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      #nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "resultapp.selectorLabels" . | nindent 4 }}