apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
  labels:
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}-{{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    leadingspaces: “       {{- .Chart.Name  }}        spaces”
    trailingspaces: “        {{ .Chart.Name  -}}        spaces”
    leadingtrailingspaces: “           {{- .Chart.Name -}}      spaces”
    indenttest: "  {{- .Chart.Name | indent 4 -}}  "
    nindenttest: "  {{- .Chart.Name | nindent 6 -}}  "
spec:
{{- if and .Values.application.feature (eq .Values.application.env "prod")}}
  replicas: 7
{{- else if eq .Values.application.env "stage" }}
  replicas: 5
{{- else }}  
  replicas: 1
{{- end }} 
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        helm.sh/chart: {{ .Chart.Name }}
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}-{{ .Chart.Name }}
        app.kubernetes.io/version: {{ .Chart.Version }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "praravind1801/helmimages:1.0.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources: 
          {{- toYaml .Values.resources | nindent 12 }}