redisapp:
  deploy: middle-deployment
  name: redisapp
  tier: middle
  podName: redisapp-pod
  containerName: redisapp-container
  releaseName: redisapp
  serviceName: redis

replicaCount: 1

image:
  repository: redis
  tag: latest

service:
  port: 6379
  targetPort: 6379
  type: ClusterIP

ingress:
  enabled: false