apiVersion: v1
kind: Service 
metadata:
  name: {{ include "voteapp.releasename" . }}-service
  labels:
    {{- include "voteapp.Labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      #nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "voteapp.selectorLabels" . | nindent 4 }}