{{- $secretName := .Values.postgresapp.serviceName -}}
apiVersion: v1 
kind: Secret 
metadata:
  name: {{ $secretName }}-secret
data:
  {{- range $key, $val := .Values.env.secret }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
type: {{ .Values.secret.type }}