apiVersion: v2
name: parentchart
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: samplehelmapp
  version: "3.0.0"
  repository: "https://aravindjordank8s.github.io/helmcharts/"
  alias: samplehelmappv3
  tags:
    - NewVersion
- name: samplehelmapp
  version: "2.0.0"
  repository: "https://aravindjordank8s.github.io/helmcharts/"
  alias: samplehelmappv2
  tags:
    - OldVersion
- name: samplehelmapp
  version: "1.0.0"
  repository: "https://aravindjordank8s.github.io/helmcharts/"
  alias: samplehelmappv1
  tags:
    - OldVersion